# Generated by Django 5.2.14 on 2026-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=180)),
                ('name_cn', models.CharField(blank=True, max_length=180)),
                ('years', models.CharField(blank=True, max_length=80)),
                ('description_en', models.TextField(blank=True)),
                ('description_cn', models.TextField(blank=True)),
                ('course_url', models.CharField(blank=True, max_length=240)),
                ('attachment', models.FileField(blank=True, upload_to='courses/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=220)),
                ('title_cn', models.CharField(blank=True, max_length=220)),
                ('body_en', models.TextField(blank=True)),
                ('body_cn', models.TextField(blank=True)),
                ('cover_image', models.FileField(blank=True, upload_to='news/')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_cn', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('faculty', 'Faculty'), ('research_staff', 'Research staff'), ('postdoc', 'Postdoctoral fellow'), ('phd', 'Ph.D. student'), ('master', 'Master student'), ('alumni_phd', 'Ph.D. alumnus'), ('alumni_master', 'Master alumnus')], max_length=30)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_cn', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='people/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('homepage', models.URLField(blank=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=240)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=220)),
                ('title_cn', models.CharField(blank=True, max_length=220)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('description_en', models.TextField(blank=True)),
                ('description_cn', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='positions/')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['status', '-publish_date', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('authors', models.TextField(blank=True)),
                ('publication_type', models.CharField(choices=[('journal', 'Journal paper'), ('book', 'Book or book chapter'), ('conference', 'Conference proceeding'), ('workshop', 'Workshop or invited seminar')], max_length=20)),
                ('venue', models.CharField(blank=True, max_length=260)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=80)),
                ('issue', models.CharField(blank=True, max_length=80)),
                ('pages', models.CharField(blank=True, max_length=80)),
                ('doi', models.CharField(blank=True, max_length=160)),
                ('external_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='publications/pdfs/')),
                ('raw_citation', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_cn', models.CharField(blank=True, max_length=160)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_cn', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='research/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(default='em+ Lab', max_length=120)),
                ('name_cn', models.CharField(blank=True, max_length=120)),
                ('subtitle_en', models.CharField(blank=True, max_length=240)),
                ('subtitle_cn', models.CharField(blank=True, max_length=240)),
                ('hero_title', models.CharField(default='em+ Lab', max_length=160)),
                ('hero_text', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid_url', models.URLField(blank=True)),
                ('google_scholar_url', models.URLField(blank=True)),
                ('address_en', models.CharField(blank=True, max_length=240)),
                ('address_cn', models.CharField(blank=True, max_length=240)),
                ('sustech_logo', models.FileField(blank=True, upload_to='site/logos/')),
                ('department_logo', models.FileField(blank=True, upload_to='site/logos/')),
                ('lab_logo', models.FileField(blank=True, upload_to='site/logos/')),
                ('hero_image', models.FileField(blank=True, upload_to='site/hero/')),
                ('professor_photo', models.FileField(blank=True, upload_to='site/profile/')),
                ('professor_name_image', models.FileField(blank=True, upload_to='site/profile/')),
                ('orcid_icon', models.FileField(blank=True, upload_to='site/icons/')),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
    ]
