# Generated by Django 5.2.14 on 2026-05-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='bio_academic_path_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_academic_path_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_conference_activity_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_conference_activity_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_impact_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_impact_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_professional_service_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_professional_service_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_sustech_appointment_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_sustech_appointment_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='biography_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='biography_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='hero_text_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='hero_title_cn',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='professor_name_cn',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='professor_name_en',
            field=models.CharField(default='Qingsha S. Cheng', max_length=160),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='professor_title_cn',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='professor_title_en',
            field=models.CharField(default='Associate Professor, SUSTech', max_length=160),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='research_focus_cn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='research_focus_en',
            field=models.TextField(blank=True),
        ),
    ]
